// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANItXkZQhmlFaOGr4Fn0Rb9VtQ83_oCfY',
    appId: '1:805488032813:web:308c3ee1f1e0aecb2c4ca4',
    messagingSenderId: '805488032813',
    projectId: 'auxiliscz',
    authDomain: 'auxiliscz.firebaseapp.com',
    storageBucket: 'auxiliscz.firebasestorage.app',
    measurementId: 'G-163KT8Y5KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi605LwCQrTN0SzM8H1bbYTTI3V8_Aqio',
    appId: '1:805488032813:android:b52361ba088ed6de2c4ca4',
    messagingSenderId: '805488032813',
    projectId: 'auxiliscz',
    storageBucket: 'auxiliscz.firebasestorage.app',
  );
}
